///////////////////////////////////////////////////////////////////////////////
// LaserTrackerUDP_senderClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "LaserTrackerUDP_senderClassFactory.h"
#include "LaserTrackerUDP_senderServices.h"
#include "LaserTrackerUDP_senderVersion.h"
#include "UDP_sender.h"

BEGIN_CLASS_MAP(CLaserTrackerUDP_senderClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_LaserTrackerUDP_sender, CID_LaserTrackerUDP_senderCUDP_sender, SRVNAME_LASERTRACKERUDP_SENDER "!CUDP_sender", CUDP_sender)
///</AutoGeneratedContent>
END_CLASS_MAP()

CLaserTrackerUDP_senderClassFactory::CLaserTrackerUDP_senderClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_LASERTRACKERUDP_SENDER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(LaserTrackerUDP_sender));
#endif //defined(TCDBG_UNIT_VERSION)
}

